export const GET_ERRORS = 'GET_ERRORS';
export const USER_LOADING = 'USER_LOADING';
export const SET_CURRENT_USER = 'SET_CURRENT_USER';
export const GET_PLACES = 'GET_PLACES';
export const PLACES_LOADING = 'PLACES_LOADING';
export const GET_VEHICLES = 'GET_VEHICLES';
export const VEHICLES_LOADING = 'VEHICLES_LOADING';
export const GET_CHARTS_PLACES = 'GET_CHARTS_PLACES';
